theme: jekyll-theme-midnight
title: Steven Saus - Author, Nuclear Medicine Technologist, Educator, Coder, Sociologist - Steve Saus
description: GitHub page of Steven Saus, author, coder, educator, freelance writer, sociologist, non-traditional student, nuclear medicine technologist, and pronoiac memebroker.
